// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrA1uUWc_P1NG4TJ6V1xtc5U8UnZx9g8Y',
    appId: '1:861718286373:web:6899aef2c805634e19afcc',
    messagingSenderId: '861718286373',
    projectId: 'flutter-app-72f03',
    authDomain: 'flutter-app-72f03.firebaseapp.com',
    storageBucket: 'flutter-app-72f03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSHWL0HbmqZfN5v5yDy5JUEoq-JgmQXKU',
    appId: '1:861718286373:android:60e8ea63434394c719afcc',
    messagingSenderId: '861718286373',
    projectId: 'flutter-app-72f03',
    storageBucket: 'flutter-app-72f03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9pkg1l7MygnKqjjBeGDc3_p81PTYOuFA',
    appId: '1:861718286373:ios:1855d21acdcdb03319afcc',
    messagingSenderId: '861718286373',
    projectId: 'flutter-app-72f03',
    storageBucket: 'flutter-app-72f03.appspot.com',
    iosBundleId: 'com.example.miniWatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9pkg1l7MygnKqjjBeGDc3_p81PTYOuFA',
    appId: '1:861718286373:ios:1855d21acdcdb03319afcc',
    messagingSenderId: '861718286373',
    projectId: 'flutter-app-72f03',
    storageBucket: 'flutter-app-72f03.appspot.com',
    iosBundleId: 'com.example.miniWatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrA1uUWc_P1NG4TJ6V1xtc5U8UnZx9g8Y',
    appId: '1:861718286373:web:507b0dc09da729b319afcc',
    messagingSenderId: '861718286373',
    projectId: 'flutter-app-72f03',
    authDomain: 'flutter-app-72f03.firebaseapp.com',
    storageBucket: 'flutter-app-72f03.appspot.com',
  );
}
